#!/usr/bin/php -f
<?php

echo "\ec"; // Clear the console

$bRun = true;
$bChanged = false;

$sPath = $argv[1] ?? ".";
$sModulesFile = $sPath . "/_modules.php";

if (file_exists($sModulesFile))
    require_once $sModulesFile;

$aModules = $aModules ?? [];

$sCurrentNameSpace = "";

$aOpts = [
    ["s[h]ow options",  "h",  "showOpts"],


    ["set [n]amespace",  "n",  function() {
        global $sCurrentNameSpace;
        $sNS = readline("namespace: ");
        $sCurrentNameSpace = ltrim($sNS, "\\");
        echo "\ec"; // Clear the console
    }],

    ["[l]ist classes",  "l",  function () {
        global $aModules;

        echo "Modules:\n", str_repeat("=", 80), "\n";

        foreach ($aModules as $sClass => $sFile) {
            echo "\t$sClass => $sFile\n";
        }

        echo str_repeat("-", 80), "\n";
    }],
    ["[a]dd class", "a", function () {
        global $aModules, $bChanged, $sCurrentNameSpace;

        $sClass = readline("Class: ");
        if (empty($sClass = trim(ltrim($sClass, "\\")))) {
            echo "abort\n";
            return;
        }

        $arr = [];
        preg_match('/(?<namespace>.*?)\\\\{0,1}(?<classname>[^\\\\]+)$/', $sClass, $arr);
        $sDefaultFileName = "./" . $arr['classname'] . ".php";
        $sClassNameSpace = $arr['namespace'];

        if(strcmp($sClassNameSpace, $sCurrentNameSpace)) 
            $sClass = $sCurrentNameSpace . "\\" . $sClass;

        $sFile = readline("File [$sDefaultFileName]: ");
        if (empty($sFile))
            $sFile = $sDefaultFileName;

        $aModules[$sClass] = $sFile;
        $bChanged = true;

        echo "\ec", "added $sClass => $sFile\n";

    }],

    ["[d]rop class", "d", function () {
        global $aModules, $bChanged;

        $sClass = readline("Class: ");
        if (empty($sClass = trim($sClass))) {
            echo "abort\n";
            return;
        }

        unset($aModules[$sClass]);
        $bChanged = true;
        echo "\ec"; // Clear the console
    }],
    ["[q]uit",  "q",  function () {
        global $bRun;
        $bRun = false;
    }]
];

function showOpts()
{
    global $aOpts;
    echo "\ec"; // Clear the console
    foreach ($aOpts as $i => $aOpt)
        echo $i, ": ", $aOpt[0], "\n";
}

//==============================================================================
// Main - Loop
//==============================================================================
showOpts();
while ($bRun) {
    echo "\nCurrent namespace: ", $sCurrentNameSpace, "\n";
    $line = trim(readline("What todo [h]: "));
    echo "\n";
    if (!$line) showOpts();
    else {
        $ran = false;
        foreach ($aOpts as $i => $aOpt) {
            if (is_numeric($line) && $i === (int)$line or ($line === $aOpt[1])) {
                $fnc = $aOpt[2];
                $ran = true;
                $fnc();
                break;
            }
        }

        if (!$ran) echo "I Could not understand you !\n";

        $line = false;
    }
}

// Save Changes if needed
if ($bChanged)
    file_put_contents($sModulesFile, "<?php\n\n\$aModules = " . var_export($aModules, true) . ";");
